### PR TITLE
Moves the algorithm code from 1 to v2

### PR DESCRIPTION
**Pull request by vitorpamplona**
Tests are passing. Let me know if I missed anything. 

This PR does 3 things: 
- Moves the version code to 2. 
- Adds the code into the base64, in the same place v1 was last time. 
- Updates all test cases to match

### CODE REVIEW

**Comment by paulmillr** [comment]
You've suggested using non-base64 character.

What if we use `@` as first char, or anything else, like `#`, `$`, `_`, `+` or `=`? Would this work for you? I want to be able to use different encodings.

**Comment by vitorpamplona** [comment]
Well, I was hoping to only add that additional character in the non-base64 encoders, but sure. We can do this as well. 

Then the character defines the encoding and the version inside defines the cryptographic algorithm. 

Btw, I am not sure if you know but there is this standard for multiple base encodings: https://github.com/multiformats/multibase

**Comment by paulmillr** [comment]
If we add non-standard base character later, that would require us to reserve such character right now: so that future clients would be able to detect and parse it. Otherwise, they would just see that it's invalid base64 and throw an unhelpful error. 

So we will have `@`/`#`-parsing logic in any case.

Multibase doesn't seem to help us much: it's only for base* encodings.

**Comment by paulmillr** [comment]
Overall i'm leaning towards your solution, but in cryptography there's https://moxie.org/2011/12/13/the-cryptographic-doom-principle.html so i'm kinda hesitant to just always parse base64 by default.

**Comment by vitorpamplona** [comment]
Very interesting attack. I am not sure how adding a char would help this because people would be doing base64decode(slice(1,n)) anyway. And since the first char codes will be no secret, there's little to learn from the additional protection. Unless I am missing something.

**Comment by paulmillr** [comment]
@vitorpamplona can you also update Kotlin impl? Make sure to scan for `@` or `#` first character in your code as well, for future-proofness.

**Comment by paulmillr** [comment]
@vitorpamplona also the `44.md` spec for in my fork of `nips` repository, with new values of salt/ciphertext/mac indexes

**Comment by vitorpamplona** [comment]
I just updated your 44.md

**Comment by vitorpamplona** [comment]
I will do the kotlin stuff tomorrow.

**Pull request merged**
